baseURL = "https://perfectbeliever.github.io/"
title = "Devendran Nehru"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 6

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Devendran Nehru"
description = "DevD's Blogging Site"
keywords = "blog,developer,personal"
info = ["Quality Engineering","DevSecOps","AI ML BigData","Tamil Poet","Site under construction - expected completion by 30/09/2025"]
avatarURL = "images/avatar.png"
dateFormat = "January 2, 2006"
since = 2024
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 10

# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []
# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/peRFectBeliever"

[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/peRFectBeliever"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://x.com/peRFectBelievr"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/devendran-nehru/"

# [[params.social]]
# name = "RSS"
# icon = "fa-solid fa-rss fa-2x"
# weight = 6
# url = "https://myhugosite.com/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blogs"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact Me"
weight = 5
url = "contact/"